name: Generate PDF 
on: [push]
jobs:
  convert_to_pdf:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          chmod +x autogeneratePDF.sh
      - uses: docker://pandoc/latex:2.9
        with:
          entrypoint: autogeneratePDF.sh
      - run: |
          ls ${{ github.workspace }}
